= MapStruct Spring Extensions {mapstructSpringExtensionsVersion} Reference Guide
:revdate: {docdate}
:toc: right
:sectanchors:
:Author: Raimund Klein

[[Preface]]
== Preface
This is the reference documentation of the MapStruct Spring Extensions, an annotation processor designed to complement the core MapStruct project with features specific to the Spring Framework.
This guide covers all the functionality provided by the MapStruct Spring Extensions. In case this guide doesn't answer all your questions just join the MapStruct https://groups.google.com/forum/?fromgroups#!forum/mapstruct-users[Google group] to get help.

IMPORTANT: This guide assumes some familiarity with the MapStruct core. If this is your first introduction to MapStruct, you might wish to start with the https://mapstruct.org/documentation/stable/reference/html/[core documentation].

You found a typo or other error in this guide? Please let us know by opening an issue in the https://github.com/mapstruct/mapstruct-spring-extensions[MapStruct Spring Extensions GitHub repository],
or, better yet, help the community and send a pull request for fixing it!

This work is licensed under the http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License].

:numbered:

include::chapter-1-introduction.asciidoc[]

include::chapter-2-set-up.asciidoc[]

include::chapter-3-mapper-as-converter.asciidoc[]

include::chapter-4-external-conversions.asciidoc[]

include::chapter-5-test-extensions.asciidoc[]

include::chapter-6-delegating-converters.asciidoc[]