/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.co.kleindelao.mapstruct.spring;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
